### ISSUE TITLE
Hourboostr logs in but doesn't idle any games

### ISSUE THREAD

**Issue by Incarceron** [Ezzpify/HourBoostr#11]
I get to the "successful" screen where the accounts are loaded and it hides to tray, but no games ever get idled. I'm not sure if I'm doing anything wrong because I've followed video tutorials and instructions in the github, but nothing works.

Here's a screenshot:
http://i.imgur.com/f4pE4E5.png

**Comment by Ezzpify** [comment]
Your steam will not appear online when you are idling, unless you enable it in the settings (which I don't recommend).
Or do you mean that hours are not getting counted at all?
