### ISSUE TITLE
Doesn't recognize a demo of a game

### ISSUE THREAD

**Issue by middleeasternfag** [Ezzpify/HourBoostr#113]
I have downloaded the demo of the game "Slime Rancher" and Singleboostr doesn't seem to recognize it, is there any way I could add this game manually? Like per steamapp id or something? Because I'd like to idle this game.

**Comment by Ezzpify** [comment]
Update game list in settings

**Comment by middleeasternfag** [comment]
lol

Am Mo., 9. Okt. 2017 um 16:10 Uhr schrieb Casper BL <
notifications@github.com>:
