### ISSUE TITLE
HourBoostr for Linux

### ISSUE THREAD

**Issue by RikoWars** [Ezzpify/HourBoostr#121]
Can you make anything like that for Linux?

**Comment by Ezzpify** [comment]
It runs on mono

**Comment by RikoWars** [comment]
How ? If I run "mono HourBoostr.exe" it says "Cannot open assembly 'HourBoostr.exe': File does not contain a valid CIL image."

**Comment by rishav394** [comment]
Happened with me too. I just tried apt-get update and all the basic stuff and reinstalled Mono. It worked flawlessly then.
