### ISSUE TITLE
Unhandled exception has occurred in your application with the SingleBoostr

### ISSUE THREAD

**Issue by Grievingx** [Ezzpify/HourBoostr#126]
This only popped up after the latest steam update, but before that it had no issues

**Comment by Aceheliflyer** [comment]
I also have gotten this issue, [here are the details](http://gist.github.com/Aceheliflyer/280a8dcf581c73aa31f083ad0d91654d) assuming they're needed.

**Comment by hellmoss** [comment]
Same.

**Comment by GijonDev** [comment]
Same here.

**Comment by smiffdev** [comment]
same here

**Comment by kermadec** [comment]
yep same here.

**Comment by projechi** [comment]
just got the error too, i too suspect the recent steam update

**Comment by Kronogenics** [comment]
Same here.

**Comment by Prophet0702** [comment]
I have this problem as well.

**Comment by ensvrd** [comment]
same

**Comment by Zaczero** [comment]
#129 
Attaching compiled project (Release)
[SingleBoostr Updated.zip](https://github.com/Ezzpify/HourBoostr/files/1565670/SingleBoostr.Updated.zip)

**Comment by smiffdev** [comment]
@Zaczero thanks! working great now :-)

**Comment by kermadec** [comment]
@Zaczero Thank you ^^

**Comment by Ezzpify** [comment]
Fixed
