### ISSUE TITLE
Does it need to install games and node.js to vps or what?

### ISSUE THREAD

**Issue by musivian** [Ezzpify/HourBoostr#13]
I really don't know how things work with VPS, Im having trouble using it. Thank you.

**Comment by Ezzpify** [comment]
You do not need to use node.js. You don't need to install any games either.
Make sure you have the latest .NET Framework installed and then run the program.

It has to be a window vps, by the way.

**Comment by musivian** [comment]
ATM Fixed.
.NET 4.5.1 lol
