### ISSUE TITLE
Microsoft .NET Framework Error

### ISSUE THREAD

**Issue by Crpsem** [Ezzpify/HourBoostr#130]
![Preview](https://i.hizliresim.com/d7pvk4.png)

Bu iletişim kutusu yerine JIT hata ayıklamayı çağırma
hakkında detaylı bilgi için bu iletinin sonuna bakın.

************** Özel Durum Metni **************
System.NullReferenceException: Nesne başvurusu bir nesnenin örneğine ayarlanmadı.
   konum: SingleBoostr.MainForm.ConnectToSteam()
   konum: SingleBoostr.MainForm.<InitializeApp>d__125.MoveNext()
--- Özel durumun oluşturulduğu önceki konumdan başlayan yığın izlemesinin sonu ---
   konum: System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass2.<ThrowAsync>b__3(Object state)

************** Yüklü Derlemeler **************
mscorlib
    Derleme Sürümü: 4.0.0.0
    Win32 Sürümü: 4.6.96.0 built by: NETFXREL2STAGE
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
SingleBoostr
    Derleme Sürümü: 3.0.1.0
    Win32 Sürümü: 3.0.1
    CodeBase: file:///C:/Users/Alperen%20AKKAYA/Desktop/SingleBoostr/SingleBoostr.exe
----------------------------------------
System.Windows.Forms
    Derleme Sürümü: 4.0.0.0
    Win32 Sürümü: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Derleme Sürümü: 4.0.0.0
    Win32 Sürümü: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Derleme Sürümü: 4.0.0.0
    Win32 Sürümü: 4.6.93.0 built by: NETFXREL2STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Derleme Sürümü: 4.0.0.0
    Win32 Sürümü: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Derleme Sürümü: 4.0.0.0
    Win32 Sürümü: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Derleme Sürümü: 4.0.0.0
    Win32 Sürümü: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Newtonsoft.Json
    Derleme Sürümü: 10.0.0.0
    Win32 Sürümü: 10.0.1.20720
    CodeBase: file:///C:/Users/Alperen%20AKKAYA/Desktop/SingleBoostr/Newtonsoft.Json.DLL
----------------------------------------
System.Numerics
    Derleme Sürümü: 4.0.0.0
    Win32 Sürümü: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Derleme Sürümü: 4.0.0.0
    Win32 Sürümü: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Derleme Sürümü: 4.0.0.0
    Win32 Sürümü: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
Steam4NET
    Derleme Sürümü: 1.0.0.0
    Win32 Sürümü: 1.0.0.0
    CodeBase: file:///C:/Users/Alperen%20AKKAYA/Desktop/SingleBoostr/Steam4NET.DLL
----------------------------------------
mscorlib.resources
    Derleme Sürümü: 4.0.0.0
    Win32 Sürümü: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_tr_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
System.Windows.Forms.resources
    Derleme Sürümü: 4.0.0.0
    Win32 Sürümü: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_tr_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

************** JIT Hata Ayıklama **************
JIT hata ayıklamayı etkinleştirmek için, bu uygulamanın veya
bilgisayarın (machine.config) .config dosyasında
system.windows.forms bölümünde jitDebugging değeri ayarlanmış olmalıdır.
Ayrıca uygulama hata ayıklama etkin durumdayken derlenmiş
olmalıdır.

Örneğin:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

JIT hata ayıklama etkinken, işlenmemiş özel durumlar
bu iletişim kutusunda işlenmek yerine bilgisayarda kayıtlı
JIT hata ayıklayıcısına gönderilir.
![1](https://user-images.githubusercontent.com/34004651/34174861-762c688e-e50b-11e7-9352-d49aecd3ef52.png)

**Comment by ajamboboy** [comment]
can you post in english?

**Comment by Crpsem** [comment]
https://github.com/Ezzpify/HourBoostr/issues/131
english!

**Comment by Dimitriblyater** [comment]
I'm getting the same problem even after latest update

**Comment by Ezzpify** [comment]
Issue has been fixed.
