### ISSUE TITLE
when I get an error like this, fix it

### ISSUE THREAD

**Issue by mertcan1955** [Ezzpify/HourBoostr#132]
1 day I encounter such a problem.when I try the new version PlayerUnknown's battlegrounds are not playing.
 http://prntscr.com/hq9f30 http://prntscr.com/hq9f6c http://prntscr.com/hq9fyv http://prntscr.com/hq9g3e
 
@Ezzpify

**Comment by sanik90** [comment]
about to issue the same thing, yes, I do facing the same issue, not sure if it the windows update or what, can someone please look into this matter?

OS: Windows 10 Creators Update

**Comment by arianaxe** [comment]
Yes I also need help

**Comment by Ezzpify** [comment]
Issue has been fixed.
