### ISSUE TITLE
No working - Error JIT

### ISSUE THREAD

**Issue by delidolu1adam** [Ezzpify/HourBoostr#133]
Bu iletişim kutusu yerine JIT hata ayıklamayı çağırma
hakkında detaylı bilgi için bu iletinin sonuna bakın.

************** Özel Durum Metni **************
System.NullReferenceException: Nesne başvurusu bir nesnenin örneğine ayarlanmadı.
   konum: SingleBoostr.MainForm.ConnectToSteam()
   konum: SingleBoostr.MainForm.<InitializeApp>d__127.MoveNext()
--- Özel durumun oluşturulduğu önceki konumdan başlayan yığın izlemesinin sonu ---
   konum: System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

************** Yüklü Derlemeler **************
mscorlib
    Bütünleştirilmiş Kod Sürümü: 4.0.0.0
    Win32 Sürümü: 4.7.2114.0 built by: NET47REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
SingleBoostr
    Bütünleştirilmiş Kod Sürümü: 3.1.0.0
    Win32 Sürümü: 3.1.0
    CodeBase: file:///C:/Users/Serhat/Desktop/SingleBoostr/SingleBoostr.exe
----------------------------------------
System.Windows.Forms
    Bütünleştirilmiş Kod Sürümü: 4.0.0.0
    Win32 Sürümü: 4.7.2114.0 built by: NET47REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Bütünleştirilmiş Kod Sürümü: 4.0.0.0
    Win32 Sürümü: 4.7.2114.0 built by: NET47REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Bütünleştirilmiş Kod Sürümü: 4.0.0.0
    Win32 Sürümü: 4.7.2053.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Bütünleştirilmiş Kod Sürümü: 4.0.0.0
    Win32 Sürümü: 4.7.2053.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Bütünleştirilmiş Kod Sürümü: 4.0.0.0
    Win32 Sürümü: 4.7.2114.0 built by: NET47REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Bütünleştirilmiş Kod Sürümü: 4.0.0.0
    Win32 Sürümü: 4.7.2102.0 built by: NET47REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Newtonsoft.Json
    Bütünleştirilmiş Kod Sürümü: 10.0.0.0
    Win32 Sürümü: 10.0.1.20720
    CodeBase: file:///C:/Users/Serhat/Desktop/SingleBoostr/Newtonsoft.Json.DLL
----------------------------------------
System.Numerics
    Bütünleştirilmiş Kod Sürümü: 4.0.0.0
    Win32 Sürümü: 4.7.2053.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Bütünleştirilmiş Kod Sürümü: 4.0.0.0
    Win32 Sürümü: 4.7.2106.0 built by: NET47REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Bütünleştirilmiş Kod Sürümü: 4.0.0.0
    Win32 Sürümü: 4.7.2102.0 built by: NET47REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
Steam4NET
    Bütünleştirilmiş Kod Sürümü: 1.0.0.0
    Win32 Sürümü: 1.0.0.0
    CodeBase: file:///C:/Users/Serhat/Desktop/SingleBoostr/Steam4NET.DLL
----------------------------------------
mscorlib.resources
    Bütünleştirilmiş Kod Sürümü: 4.0.0.0
    Win32 Sürümü: 4.7.2053.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_tr_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
System.Windows.Forms.resources
    Bütünleştirilmiş Kod Sürümü: 4.0.0.0
    Win32 Sürümü: 4.7.2053.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_tr_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

************** JIT Hata Ayıklama **************
JIT hata ayıklamayı etkinleştirmek için, bu uygulamanın veya
bilgisayarın (machine.config) .config dosyasında
system.windows.forms bölümünde jitDebugging değeri ayarlanmış olmalıdır.
Ayrıca uygulama hata ayıklama etkin durumdayken derlenmiş
olmalıdır.

Örneğin:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

JIT hata ayıklama etkinken, işlenmemiş özel durumlar
bu iletişim kutusunda işlenmek yerine bilgisayarda kayıtlı
JIT hata ayıklayıcısına gönderilir.

**Comment by Ezzpify** [comment]
Fixing when I am home from vacation

**Comment by Shiigehiro** [comment]
Same error

**Comment by LonerD** [comment]
New version released this Dec 27, 2017
Still not fixed

**Comment by Ezzpify** [comment]
Issue has been fixed.
