### ISSUE TITLE
SingleBoostr Problem

### ISSUE THREAD

**Issue by TrolluXe** [Ezzpify/HourBoostr#135]
************** Ausnahmetext **************
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei SingleBoostr.MainForm.ConnectToSteam()
   bei SingleBoostr.MainForm.<InitializeApp>d__132.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

**Comment by TrolluXe** [comment]
Well, using the fixed version now. 
https://github.com/Ezzpify/HourBoostr/pull/129
Just add his Steam4NET to your SingleBoostr

**Comment by neXus26** [comment]
Wait how do you just add Steam4NET to Single booster?

**Comment by TrolluXe** [comment]
by a"dd" I mean to overwrite the old one

**Comment by N0keya** [comment]
Where are you getting this Steam4NET from? As there is one in the singleboostr folder but I am guessing you are talking about another file called that. Where do I get this?

**Comment by TrolluXe** [comment]
[https://youtu.be/w0-Dhh9LPnE](url)

**Comment by SkyrenOfficial** [comment]
I did this also, pure logic though...

1. Download [url=https://github.com/Ezzpify/HourBoostr/files/1565668/SingleBoostr.Updated.zip]this[/url]
2. Unzip and copy Steam4NET into updated official version

**Comment by Ezzpify** [comment]
Issue has been fixed.
