### ISSUE TITLE
Running in android...?

### ISSUE THREAD

**Issue by rishav394** [Ezzpify/HourBoostr#137]
It works perfectly in my PC and i boost 3-4 accounts simultaneously. It would be kinda great if it could be possible to run it on a rooted android maybe. A "How-To" would be nice. Thanks and great job.

**Comment by SkyrenOfficial** [comment]
There is tutorial somewhere on YouTube. I believe the link was on Discord App.

**Comment by rishav394** [comment]
Ya i tried that. It works perfectly. I just think if there would be an android app that uses that process then it would be great, I think ill develop it.
