### ISSUE TITLE
HourBoostr 3.2.1 doesnt work with mono

### ISSUE THREAD

**Issue by blackzafiqz** [Ezzpify/HourBoostr#147]
![image](https://user-images.githubusercontent.com/17066308/35274291-8312e5e2-0076-11e8-9641-a8db4745f9d4.png)

As you can see mono doesnt work with HourBoostr and doesnt give any log. I attached my system information in picture above. Hope you can solve this soon.

p/s: mono works with HourBoostr v3.2.0 below

**Comment by rishav394** [comment]
Just use the previous version. It still works flawlessly.
