### ISSUE TITLE
A folder called "Sentryfiles" is created. Why?

### ISSUE THREAD

**Issue by sirajuddin97** [Ezzpify/HourBoostr#15]
Every time I run HourBoostr.exe, a folder named "Sentryfiles" is created, where there is another file inside named "myusername.sentry" (for example "sirajuddin97.sentry"). Why's that?

Sentry is a program that cracks accounts and passwords, no?

**Comment by Ezzpify** [comment]
https://github.com/Ezzpify/HourBoostr/blob/master/HourBoostr/Bot.cs#L259
