### ISSUE TITLE
Run from android phone?

### ISSUE THREAD

**Issue by ihajelo** [Ezzpify/HourBoostr#16]
HourBoostr works just fine on my PC , but was wondering is there any chanse for it to work on a android phone somehow?

**Comment by capybarasIareIamazing** [comment]
that would be awesome. i'd charge my cellphone all night just to idle my games
(sorry for the english, i'm brazilian)

**Comment by Ezzpify** [comment]
That would require .. some time. I would recommend you to either get a free VPS or look into paying for one.

https://www.inmotionhosting.com/support/website/what-is-vps-hosting

TL;DR virtual computer running in the 'clouds'
