### ISSUE TITLE
Hi im new userWhat is The Different single boost = Hourboostr

### ISSUE THREAD

**Issue by neverzz9** [Ezzpify/HourBoostr#166]
Please let me know 
Single boost
Can use Boost hour with many game in same time // also a card drop

Hourboostr
Also using boot hour with many game

Question 
So what is the different ? i cant see what is the different 2 of this also can boost single game and many game

Thx from new user

**Comment by BlackYuzia** [comment]
@neverzz9 

# Single Boost
1)If you use **SB**, you can boost && play games. 
1.1) **SB** used for boost other games when you play OR boost games when your PC work (ON).
>For example:  You play in CS:GO, and boost Dota 2, TF2 etc

# Hour Boost
2)If you use **HB**, you can ONLY boost games. If you try play game, you stop boost time.
2.1) **HB** used for 24/7 boost games.

PS: You can boost (for both application) 33 games. 

Ask about more, you can in **Discord Channel**

**Comment by neverzz9** [comment]
Thank you @BlackYuzia
