### ISSUE TITLE
the program does not save passwords

### ISSUE THREAD

**Issue by MrFurison** [Ezzpify/HourBoostr#18]
When I click to `save your password`, the program saves. But when a person comes to account, the program deletes the line of code where the saved passwords

**Comment by MrFurison** [comment]
in windows amazon (8  mb)

**Comment by MrFurison** [comment]
windows server 2012 r2 standart
Plz fix this bug

**Comment by MrFurison** [comment]
hello?Programmer?

**Comment by MrFurison** [comment]
Ezzpify u program the best.but please fix the error PLEASE

**Comment by Ezzpify** [comment]
Please test the newest version.
