### ISSUE TITLE
Cs Go & Games simultaneously

### ISSUE THREAD

**Issue by ghost** [Ezzpify/HourBoostr#187]
I can receive vac ban if I use HourBoostr in cs go, Euro Truck Simulator 2, Team Fortress ? 
And I can play 30 games at once and to be safe?

**Comment by ArunPrakashG** [comment]
u can play 33 games [Steam limit] at once and not get banned. 
just make sure that when you are launching a game on your pc, stop the boost, then start it again when u quit the game.
