### ISSUE TITLE
Can you get banned for doing this?

### ISSUE THREAD

**Issue by Lonick32** [Ezzpify/HourBoostr#190]
title says it all

**Comment by ArunPrakashG** [comment]
Well, to be completely honest, 
The program itself, is safe.
It depends on how you use it.
If you dont run more than a valid number of accounts (10 per IP)
then you wouldn't have any issues.
More than that means you are playing with fire.
I mean, valve knows there are Hour Boosters out there, they can easily identify who is a bot and who isn't, if your boosting is causing issues with their network, they will surely take the necessary steps.

**Comment by Lonick32** [comment]
> 
> 
> Well, to be completely honest,
> The program itself, is safe.
> It depends on how you use it.
> If you dont run more than a valid number of accounts (10 per IP)
> then you wouldn't have any issues.
> More than that means you are playing with fire.
> I mean, valve knows there are Hour Boosters out there, they can easily identify who is a bot and who isn't, if your boosting is causing issues with their network, they will surely take the necessary steps.

I am using it on my main ONLY so I should be safe right?

**Comment by ArunPrakashG** [comment]
You are safe. dont worry :D

**Comment by Lonick32** [comment]
ight
