### ISSUE TITLE
Hours not counting

### ISSUE THREAD

**Issue by toscitt** [Ezzpify/HourBoostr#2]
I have last release (1.7.2) and hours arent counting. The games should restart every what time ? Thanks

**Comment by Ezzpify** [comment]
Hello! Are you sure they're not counting? How long have you left it open for?
Games will restart every 180 + (rand(30, 60)) minutes

**Comment by toscitt** [comment]
For like 45 minutes.. But now they're counting ! Really sorry for this useless post. Thank you again for this software ! Everything is perfect

**Comment by Ezzpify** [comment]
No worries, glad it works!
