### ISSUE TITLE
Newest Version 1.9 - No CD When Logging In Elsewhere

### ISSUE THREAD

**Issue by Doniiii** [Ezzpify/HourBoostr#20]
Hey, 

Doesn't seem like the newst version is waiting 20 min after 3 failed login attempts like the older version did. Would be greatly appriciated if that was added again, it was really neat when you had it on a VPS. 

Regards,

**Comment by Ezzpify** [comment]
Thanks for pointing that out, I will have that re-added!

**Comment by Ezzpify** [comment]
Fixed
