### ISSUE TITLE
Invalid two factor code! Try again

### ISSUE THREAD

**Issue by MrFurison** [Ezzpify/HourBoostr#21]
http://prntscr.com/bxxcn4
I understand you tired. but it begins again. I ran to the Amazon and on my PC, but this time Problem. Family viewing is not. How to fix it?

**Comment by MrFurison** [comment]
http://rgho.st/7ylBDS9Qh

**Comment by MrFurison** [comment]
work password dont work

**Comment by MrFurison** [comment]
![screenshot_9](https://cloud.githubusercontent.com/assets/20472156/17176635/4a7085e0-5416-11e6-828b-9545acbfe471.png)
mmm....what is this?

**Comment by MrFurison** [comment]
how to fix it?

**Comment by Truth91** [comment]
@MrFurison 
try deleting your sentry files and try again...
if that doesn't work. try to make a new .json settings file.

**Comment by MrFurison** [comment]
again

**Comment by MrFurison** [comment]
ezz wtf how to fix this
