### ISSUE TITLE
Add Exception for Wrong PW and wrong Auth Code.

### ISSUE THREAD

**Issue by Truth91** [Ezzpify/HourBoostr#23]
i have faced this issue, it would give me an exception error where it wouldn't accept the pw's it would just keep looping connecting in 3 seconds with both auth code and wrong pw..

**Comment by Doniiii** [comment]
This isn't a bug. Seems like the cooldown system he/she added in the last version is not in the newest one. (1.9) I made a thread about this earlier this week, you can find it below. I'm sure it will be added again soon. In the meantime I recommend you using the older version with the cooldown system in place.

**Comment by Ezzpify** [comment]
Should be fixed
