### ISSUE TITLE
24/7 Boosting (vps) ? Posibble?

### ISSUE THREAD

**Issue by c1kaaacsgo** [Ezzpify/HourBoostr#24]
Is there any way to install this on vps so it will farm hour 24/7 ?

**Comment by Truth91** [comment]
i know it can be done If you have Windows VPS, simply upload your files to the vps and run the application!

**Comment by c1kaaacsgo** [comment]
Yo. Thanks,but how will i run JsonHelper and others if i dont have remote access to vps, i have only putty (terminal) for it?

**Comment by Doniiii** [comment]
I remotely installed Teamviewer and did everything through that, Pretty simple and easy actually, would recommend it.

**Comment by c1kaaacsgo** [comment]
You can install teamviewer on vps really?

**Comment by Ezzpify** [comment]
You can run this on a windows vps, yes

**Comment by bambino7k** [comment]
Can anyone make a Video or a text doc, with the necessary info... 
and maybe some links to some good and cheap VPS services 

:D
