### ISSUE TITLE
170 games not idling properly!

### ISSUE THREAD

**Issue by Truth91** [Ezzpify/HourBoostr#25]
I have a total of 170 games on my account, i have added all of them in the idler [http://puu.sh/qhgJs.png](url) example doesn't go all the way down.. but the idler is only idling 33 games [http://puu.sh/qhgO5.jpg](url) its stopping at game number 33.. and it doesn't idle 34 as you can see from the second link.. is this the way its made? or i can't idle any more than 33 games at the same time ?

**Comment by Doniiii** [comment]
There is a maximum amount of games you can idle at the same time. I'm not sure what the number is but I'm guessing it's 33 if that's what you're stuck on.

**Comment by Ezzpify** [comment]
There's a Steam limit of around 30ish games. I guess it's confirmed 33 now. You can't exceed this, even on the client as far as I know.
