### ISSUE TITLE
connecting to steam...

### ISSUE THREAD

**Issue by triggerboater** [Ezzpify/HourBoostr#26]
HourBoostr was working just fine for me earlier, but recently the hourboostr is getting stuck when trying to connect to steam. All it says is "Connecting to steam", then it tries to reconnect, but it just repeats this process forever.

**Comment by Doniiii** [comment]
Have you tried clearing DNS cache and redownload the program? If not I recommend trying it.

**Comment by triggerboater** [comment]
I redownloaded the program earlier, flushing the dns didnt work either.

**Comment by Ezzpify** [comment]
Does logging in manually with the Steam Client / Steam Website work?

**Comment by violetaseks-collab** [comment]
Good afternoon, dear developer! Stopped connecting to accounts in HourBoostr: it says “incorrect login or password.” Everything was fine, I can log into my Steam account on the website or in the application, but it won’t let me into HourBoostr, although 9 days ago everything was fine. I came in, please fix the entrance.

<img width="378" height="106" alt="Image" src="https://github.com/user-attachments/assets/a8bdf8f4-fe26-4571-b88f-e6a27832aec0" />

warn Servise unhadlet Eresult respone plasse report this issue
