### ISSUE TITLE
IT WONT STOP DUDE PLZ HELP

### ISSUE THREAD

**Issue by NovaCrab** [Ezzpify/HourBoostr#29]
I did everything right, but when i try to idle, it idles, but IT SAYS IM OFFLINE FOREVER AND IT LITERALLY WONT STOP IDLING. I have tried everything i could to try to make it stop like closing the tab, restarting steam, and IT WONT STOP. I JUST WANNA PLAY MY GAMES. PLZ HELP ME URGENTLY!!!!!!!!!!!!!!!

**Comment by Ezzpify** [comment]
[Can't Stop Won't Stop](https://www.youtube.com/watch?v=R5xzaDo5Q54)

Just close HourBoostr and start the Steam Client and login? Try restarting your pc if this doesn't work somehow.
