### ISSUE TITLE
Invalid password

### ISSUE THREAD

**Issue by DARKKi** [Ezzpify/HourBoostr#3]
I have 100% sure i wrote down the correct password but it still says InvalidPassword - Invalid password! Try again

![hourboostr](https://cloud.githubusercontent.com/assets/5562502/14286949/a1c929e8-fb59-11e5-855a-acd276cd9b39.png)

**Comment by Crypt-ix** [comment]
Are you sure you're not writing the wrong password? Sometimes what could happen is you type in the incorrect username.

Make sure caps-lock isn't active when typing your password.

any luck?

**Comment by DARKKi** [comment]
Sorry but no luck.

I checked the capslock and also directly pasted the password there but no dice :(

Can you put your password into config file btw?

**Comment by Crypt-ix** [comment]
Don't think so with this build. It could be that you're receiving an authentication error which isn't handled by this tool yet. I haven't been active enough to give you a proper answer (as I haven't skimmed through the latest build) but I'm not sure, it could be the mobile authentication?

What happens if you attempt to login through a browser / steam client?

**Comment by DARKKi** [comment]
Mobile, Web and Steam Client work fine

**Comment by Crypt-ix** [comment]
are you using the latest release ? v1.7.3.1
https://github.com/Ezzpify/HourBoostr/releases/

**Comment by DARKKi** [comment]
Yes i am. Just downloaded the program yesterday for the first time

**Comment by Crypt-ix** [comment]
are you using a single account or is it more than one?

**Comment by DARKKi** [comment]
I use multiple accounts but they are not running on this machine

**Comment by Crypt-ix** [comment]
Try just using that single account (shown on picture) on HourBoostr.

**Comment by Ezzpify** [comment]
Does your password contain any unusual characters?

**Comment by DARKKi** [comment]
only normal characters, numbers and !

**Comment by Ezzpify** [comment]
That's very strange. Are you running it from a VPS? Have you tried logging into the account via browser to be sure your IP isn't blocked or something else?

**Comment by DARKKi** [comment]
No i am not running it from VPS. And i have logged in via browser

**Comment by Ezzpify** [comment]
Logging in via Steam Client works as well?

**Comment by DARKKi** [comment]
Yeah, no problem with either one

**Comment by Ezzpify** [comment]
Can you try again now with the updated version?

**Comment by Ezzpify** [comment]
Closing this since I'll assume it works.
