### ISSUE TITLE
Virus

### ISSUE THREAD

**Issue by rahiem2000** [Ezzpify/HourBoostr#30]
This is a virus and when I download it my av doesnt allow it. And with the other versions it was no problem... Any explanation?

**Comment by Ezzpify** [comment]
Can you scan the individual files and tell me which ones your anti-virtus considers a virus?
As always, the good thing about Open Source programs is that you can download the source and compile it yourself.

**Comment by rahiem2000** [comment]
It is only the exe one. Do you have a tutorial of how to compile it maybe im not so smart :(.

**Comment by Ezzpify** [comment]
Can you give me the logs the anti-virtus gives you about the file?
If you want to compile it yourself you need an IDE, I would recommend Visual Studio.

**Comment by rahiem2000** [comment]
Yeah I have visual studio. How can I see the logs?

**Comment by rahiem2000** [comment]
Im using widnwos defender btw

**Comment by Ezzpify** [comment]
So it just says "it's a virtus"? Can you give me a screenshot?

**Comment by rahiem2000** [comment]
Yeah its like trojan detected cant see logs dont have the file either.

**Comment by Ezzpify** [comment]
Can you give me a screenshot of what Windows Defender says about the file?

**Comment by rahiem2000** [comment]
It says nothing anymore because I dont have the file anymore.

**Comment by rahiem2000** [comment]
But can you explain how to compile it? been using this program so long but now my av says its a virus

**Comment by Ezzpify** [comment]
Download the source, then open the .sln in Visual Studio.
Can you download the file again, open it, then screenshot whatever your Anti-Virus says?

**Comment by rahiem2000** [comment]
This is really weird now i dont get a popup :O.

**Comment by rahiem2000** [comment]
I opened the sln what do I need to do now?

**Comment by Ezzpify** [comment]
Weird that you didn't get the pop-up a second time.
Should it happen again, please take a screenshot of it.

At the top you go Build -> Build Solution

![preview](http://i.imgur.com/O8mQoFL.png)

**Comment by rahiem2000** [comment]
Did that

**Comment by Ezzpify** [comment]
You'll be able to find the HourBoostr.exe in bin folder
Do the same for Settings.exe project if you want that

**Comment by Crypt-ix** [comment]
![Virus Detected from BitDefender](http://i.imgur.com/F349pjb.png)

[VirusTotal Scan](https://www.virustotal.com/en/file/55443fb1dd5e313fa4735f53d40ec9e1671667c2731c42907c17c0ff4336f661/analysis/1470201476/)

This is with the latest build v1.9.1:
MD5: 8BB63AE96415E486706D2A7CED74B288

**Comment by rahiem2000** [comment]
^

**Comment by Crypt-ix** [comment]
VxStream Sandbox Automated File Analysis
(Verdict: malicious; Label: Gen:Variant.MSILPerseus; TS: 29/100; AV: 16%):
 https://www.hybrid-analysis.com/sample/55443fb1dd5e313fa4735f53d40ec9e1671667c2731c42907c17c0ff4336f661?environmentId=100

**Comment by Ezzpify** [comment]
I'm not entirely sure what's triggering this..
I've gotten more reports of people adding me and telling me that it gets automatically removed.
I'll try and look into the updates I made and see what triggers it exactly... Very annoying.

For now, people who are worried about a virus, download the source, go through it, make sure there is no malicious code anywhere, then compile it yourself and run it, :)

**Comment by Ezzpify** [comment]
I built the new version against framwork v4.6.1 again instead of v4.5.1
No idea if that helps. 

I also removed some redundant code from SteamWeb.cs since it is used in SteamTrade.dll from SteamBot (by Jessecar96) which has been used in the past to steal items, thus flagging SteamTrade.dll as a virus.
I have only been using a very small part of that library's code, but I removed even more now just to be certain.

**Comment by Ezzpify** [comment]
Closing this as I have not gotten any reports about the new version having any problems with anti-virus.
Seems like the target framework might have caused it somehow ??

**Comment by Crypt-ix** [comment]
![image](https://cloud.githubusercontent.com/assets/16103757/17481571/35a66116-5dc1-11e6-85ab-884609b4e61e.png)

**Comment by Ezzpify** [comment]
Re-opening issue since it still seems to be a problem
