### ISSUE TITLE
account limit/game limit

### ISSUE THREAD

**Issue by kubagosth** [Ezzpify/HourBoostr#33]
How many accounts i can boost at once ?
What is the limit of games i can idle  ?

**Comment by Ezzpify** [comment]
There's no account limit on this side, but I wouldn't recommend overdoing it. Steam might not like seeing 50+ accounts being idled from one IP, but what do I know. I've never boosted over 30 accounts before.
As for games, I think there's a limit of around 33 games per account. This is a restriction on Steam's side.
