### ISSUE TITLE
Password not accepted

### ISSUE THREAD

**Issue by LexalyQPAD** [Ezzpify/HourBoostr#42]
![d0tbnzhzusq](https://cloud.githubusercontent.com/assets/22733552/19321478/d483353c-90bd-11e6-8de0-ad49954320cc.jpg)

**Comment by rocket1337** [comment]
same problem

**Comment by MystikalE** [comment]
Remove login key from the program and try again.

**Comment by mikashe321** [comment]
Clearly Tuesday maintenance problems,should be fine next day.
