### ISSUE TITLE
'Reconnect in 3s' too many times -> Invalid Password

### ISSUE THREAD

**Issue by tkien212** [Ezzpify/HourBoostr#5]
I logged in to play a game ~60 mins. During that 60 mins, the bot keep trying to reconnect every 3s. And finally, it said invalid password. (maybe steam block connection?)

I tried to turn off and on again, but all of my accounts got invalid password.
I can still login using steam client.

Screenshot: http://puu.sh/o9fj2/41665d5ede.png

**Comment by Ezzpify** [comment]
Hello, when the bot was trying to connect, did it successfully connect each time and then disconnect again, or did it get stuck at "Reconnecting..."?

**Comment by tkien212** [comment]
It looks like 'it successfully connect each time and then disconnect again'

**Comment by tkien212** [comment]
the latest update fixed this problem :)
