### ISSUE TITLE
Connecting to steam and reconnecting over and over V2.1.3.2

### ISSUE THREAD

**Issue by dustyroo** [Ezzpify/HourBoostr#51]
It will keep reconnecting over and over . http://i.imgur.com/qkXr1yz.png (covered up my name)

I have to delete file {GlobalDB.hb} and folder {Sentryfiles}

then it will work one time.

**Comment by joeytee** [comment]
Exact same problem for me on my new Windows server.  My other server(s) work fine.

Also works for me on my home Desktop, but not on my server.

It will log in 1 or 2 accounts and then fail on the rest, stuck in a reconnecting loop.  Deleting those files/folders you said also makes mine work again for 1 or 2 accounts but then same problem.

Never had this issue before.

**Comment by Ezzpify** [comment]
Can you try the older versions and see if you have the same problem?

**Comment by Ezzpify** [comment]
https://github.com/Ezzpify/HourBoostr/releases/tag/1.9.2 this version

**Comment by dustyroo** [comment]
Same issue

**Comment by dustyroo** [comment]
That version works flawless
