### ISSUE TITLE
Windows Server 2012 steam reconnecting loop

### ISSUE THREAD

**Issue by joeytee** [Ezzpify/HourBoostr#53]
Hi

I've used HourBoostr many times before on multiple servers but I'm having problems this time around.

I've done a straight copy of the files/folders from my working server onto the new one and hourboostr either doesn't connect at all or connects just 1 account and then fails to log in to any more, it will say connecting to steam and then reconnecting over and over again.

I've tried a fresh copy (latest build) and the exact same thing happens.

Any idea what would be causing this?

Thanks.

**Comment by joeytee** [comment]
Now 2 hours later they all start connecting, reaches 80% of the way through and one fails to connect saying wrong password.  I check it manually and it's fine, so I restart hourboostr and now every single account says wrong password even though they are clearly not.

**Comment by Ezzpify** [comment]
Some people are reporting similar problems. Can you try older versions of HourBoostr and see if that works?

**Comment by joeytee** [comment]
An hour after I posted the last comment it stopped saying wrong password (without me changing anything) and all my accounts are connected now.  Really strange...

If it starts messing up again I'll try another version, any particular one you recommend trying?

Thanks a lot for the software by the way, it's great, been using it for a few months now :)  First time I've ever had problems.

**Comment by Ezzpify** [comment]
Good thing it's working now, but if it happens again please try this version: https://github.com/Ezzpify/HourBoostr/releases/tag/1.9.2

Glad you like my project though! :-)
