### ISSUE TITLE
Hi! If necessary, I can help you translate into Chinese.

### ISSUE THREAD

**Issue by 123wbx321wbx** [Ezzpify/HourBoostr#54]
Hi! If necessary, I can help you translate into Chinese.

**Comment by Ezzpify** [comment]
Hello. Sure, that would be helpful.
You can find the English version here: http://steamcommunity.com/groups/HourBoostr/discussions/0/154644928866366863/

Reply with the translation in that thread or here.
Thanks for contributing! :)

**Comment by 123wbx321wbx** [comment]
I have completed the translation, published in the Steam Groups.
User Name: 氷% lolix is me.
