### ISSUE TITLE
does HourBoostr  cause any band or vac ? 

### ISSUE THREAD

**Issue by 123khaled123** [Ezzpify/HourBoostr#55]
Hello, I'm new to this idle thing and wanted to check if it's okay or will i receive a banned or vac ? because my account is level +200 and dont want to waste it with vac. Thank you

**Comment by Ezzpify** [comment]
You won't and can't get vac banned. If you are super paranoid, don't run HourBoostr or SingleBoostr while playing a VAC protected game. But again, no reports of anyone being banned. I use it all the time when playing CSGO.

**Comment by 123khaled123** [comment]
Thank you very much, its quite useful. i just have couple question, first no matter how many games i put in the program it wont run more than 30? Second, can i still be online and play any offline game while boosting ?
