### ISSUE TITLE
Idling works, but is being weird.

### ISSUE THREAD

**Issue by PuppyLover101** [Ezzpify/HourBoostr#56]
Shows Grand Theft Auto V but shows it as "Image not available" and it doesnt come up as the legit game (Notice the legit one has hours and has an image.)

http://i.imgur.com/1X8g8z5.png

**Comment by Ezzpify** [comment]
You might be using the wrong ID for the game. Is this HourBoostr or SingleBoostr?

**Comment by PuppyLover101** [comment]
This is SingleBoostr.
