### ISSUE TITLE
What VPS should i use ?

### ISSUE THREAD

**Issue by mariodaelizabeth** [Ezzpify/HourBoostr#58]
Dear Ezzpify,
Man.. just want to say... you HourBoostr is really fcking fcking AWESOME ! cheers !! haha
Works like a charm and smooth... everything is ok in my personal notebook (Windows 8.1 )
Do you know what VPS spesification should i use ?
Can i use VPS Digital Ocean ? and how ?

Thank you very much for your time and a great HourBoostr open source project ;)

**Comment by Ezzpify** [comment]
Hello, and thanks!
Any vps that run windows will work fine. There are many available at different price ranges. If you just wish to run HourBoostr then you can go for a very cheap one. I use OVH personally, but I run more projects other than HourBoostr, so it would be a bit of an overkill to get that.

Just google for windows vps and you'll find plenty available.
