### ISSUE TITLE
Add a feature

### ISSUE THREAD

**Issue by SkyrenOfficial** [Ezzpify/HourBoostr#59]
I've been using HourBoostr for pretty long time now.
SingleBoostr mainly solved the issue of "account being played on" while you had to restart HourBoostr in case to play a game since connectivity was buggy.
What am I asking is if it's possible to make HourBooster to bypass this connectivity issues where when you login to the currently boosting account, you will be able to connect to the community and play a game.

Thanks

**Comment by Ezzpify** [comment]
I am not quite sure how to solve it. I did look at it a while ago and added something in hopes that it would solve it but it doesn't work very well.

**Comment by SkyrenOfficial** [comment]
Not a big deal here, latest release rocks anyways. Keep it up, dood!
