### ISSUE TITLE
Hourboostr won't connect to steam during the process.

### ISSUE THREAD

**Issue by w0wzers** [Ezzpify/HourBoostr#6]
So I don't know if this is meant to be like this but when I am logged in on my steam account on steam itself it says "A connection to the friends network could not be established. Steam will automatically retry connection until the service becomes available"

If so it would be great if you could allow steam to function normally without being in-game while using HourBoostr.

**Comment by dustyroo** [comment]
Im having the same issue, can someone help?

**Comment by Ezzpify** [comment]
Hello. I am doubtful it can be achieved but I will look into it.

**Comment by dustyroo** [comment]
Do you want some pics or something to help you with this?

**Comment by Ezzpify** [comment]
I am aware of the issue. For now you can have it running on a VPS.

**Comment by Ezzpify** [comment]
If you are interested to write a solution for it, feel free to make a pull request of course. (I think it's pull request?)

**Comment by dustyroo** [comment]
How to I install and run it on a vps?
