### ISSUE TITLE
[Paid Request] Connection to a server and idle

### ISSUE THREAD

**Issue by unusual917** [Ezzpify/HourBoostr#60]
Hi Ezzpify!
This is something that I have been looking for, and also tried using the npm steam module with no luck.
I'm trying to idle multiple accounts on a linux vps, but not just idle in game, but also idle in a server.

Can you make something like this? I'm willing to pay for your time.

**Comment by unusual917** [comment]
seems like it isn't easy to make it idle on a server, since that server setting was for steam servers rather than community severs.
IF someone can make something like this for community server idling, I will be willing to pay good money for it. msg me on github or here.

**Comment by Ezzpify** [comment]
You would need some sort of client-less technique to achieve this. Not sure if it's even possible. You would need to simulate the game itself, which I am not sure if it's possible - or it would be a hell of a work.

Good luck though
