### ISSUE TITLE
Request for SingleBoostr or HourBoostr

### ISSUE THREAD

**Issue by emiann12** [Ezzpify/HourBoostr#63]
Vet att du är svensk så jag skriver detta på svenska hoppas det går bra.

Så jag har använt både HourBoostr och SingleBoostr och dem funkar jätte bra och efter jag använt dem ett tag så märkte jag att jag hade 240 timmar senaste 2 veckorna på steam det är ju nästan helt omöjligt.
Och så mycket spelar jag inte och inte haft på singleboostr så länge heller. Men jag fattade då att om man boostar mer en ett spel så stackar timmarna med varandra och jag undrar då om det är möjligt för dig eller överhuvudtaget att du kanske kan adda en feature som låter dig ha på flera Game API's eller vad du nu går på för att boosta timmarna utan att ha på spelet. Så kanske man kan ha på samma spel I SingleBoostr många gånger så går tiden mycket snabbare så 1 timma = 3 timmar tex om du har många på.

Vore jätte kul om du kunde adda detta tack så mycket <3

**Comment by Ezzpify** [comment]
"Men jag fattade då att om man boostar mer en ett spel så stackar timmarna med varandra"
Korrekt

" och jag undrar då om det är möjligt för dig eller överhuvudtaget att du kanske kan adda en feature som låter dig ha på flera Game API's eller vad du nu går på för att boosta timmarna utan att ha på spelet. Så kanske man kan ha på samma spel I SingleBoostr många gånger så går tiden mycket snabbare så 1 timma = 3 timmar tex om du har många på."
Inte möjligt, tyvärr. :/

**Comment by emiann12** [comment]
Ohh okej tack för ett så snabbt svar :D Föresten hur lärde du dig att koda?

**Comment by emiann12** [comment]
kan jag få ett privat program av dig som jag skulle kunna ha nytta av? Om du nu godkänner detta skulle ajg villa ha en .exe som fungerar som en makro så när jag startar .exe'n frågar den vilken knapp jag vill ha som knapp att göra makron. Sen när jag klickar den knappen så spammar den a,d,a,d,a,d,a,d,a,d,a,d,a,d inte för snabbt men inte långsamt och jag menar a,d,a,d,a,d,a,d,a,d,a,d tills som stänger av makron
vore skit nice, behöver inte vara anvancerat heller, tack 🍡

**Comment by Ezzpify** [comment]
>Föresten hur lärde du dig att koda?

Började med att programmera hacks till MapleStory 6 år sedan typ genom att följa en step-by-step guide. Sen ville jag lägga till mer grejer och antar att det var då jag började lära mig att koda.

>kan jag få ett privat program av dig som jag skulle kunna ha nytta av?

Nja... Det finns många macro program redan. Om du har en steelseries/corsair/razer mus eller tangentbord så får du med macro programs som du kan använda dig av. Om du inte har det så kan du bara googla på auto clicker, macro program eller vad som helst. :)
