### ISSUE TITLE
Properly remove the tray icon when closing HourBoostr

### ISSUE THREAD

**Issue by sapphyrus** [Ezzpify/HourBoostr#65]
When you close HourBoostr using taskkill / taskmanager the tray icon stays but when you hover over it disappears. I'm automatically updating the config and restarting hourboostr to make it reload the settings so over time many Icons accumulate in my tray.

Doing this on close would fix it:
`mTrayIcon.Visible = false;`
`mTrayIcon.Dispose(); 
`

**Comment by Ezzpify** [comment]
Thanks. I will add this for the next release. :)

**Comment by sapphyrus** [comment]
ty, looking forward to it
