### ISSUE TITLE
Request for Linux version

### ISSUE THREAD

**Issue by sanik90** [Ezzpify/HourBoostr#69]
hi @Ezzpify, love your app, been using it for quite a while on Windows, is there any possibilities for Linux version? :)

**Comment by Ezzpify** [comment]
I have plans for that, yes! Not right now though, I am a bit busy. But soon(tm) along with new update of SingleBoostr.

**Comment by sanik90** [comment]
@Ezzpify nice, looking forward to it :)

**Comment by Ezzpify** [comment]
Added
