### ISSUE TITLE
Accounts sleeping twice in a row

### ISSUE THREAD

**Issue by StrafeHack** [Ezzpify/HourBoostr#7]
I'm currently using 3 accounts and every restart one of the accounts will sleep twice in a row. Here's a screenshot showing the issue, this has happened consistently for 2 days now, it is the same account each time.

http://i.imgur.com/DGYxBlg.png

**Comment by Ezzpify** [comment]
Hello. Each account will restart the games every 3 hours (+ random 1-60 minutes) to ensure the hours are being logged properly. Each restart takes roughly 30 seconds.

You can disable this if you want in the settings file.
