### ISSUE TITLE
Reconnecting Constantlly

### ISSUE THREAD

**Issue by sp3sh** [Ezzpify/HourBoostr#71]
Initializing SteamDirectory ...
xxxx [6/3/2017 15:45:05] Info: Connecting to Steam ...
xxxx [6/3/2017 15:45:11] Info: Reconnecting in 3s ...
xxxx [6/3/2017 15:45:14] Info: Connecting to Steam ...
xxxx [6/3/2017 15:45:19] Info: Reconnecting in 3s ...
xxxx [6/3/2017 15:45:22] Info: Connecting to Steam ...
xxxx [6/3/2017 15:45:27] Info: Reconnecting in 3s ...
xxxx [6/3/2017 15:45:30] Info: Connecting to Steam ...
xxxx [6/3/2017 15:45:35] Info: Reconnecting in 3s ...
xxxx [6/3/2017 15:45:40] Info: Connecting to Steam ...
xxxx [6/3/2017 15:45:45] Warn: Too many disconnects occured in a short period of time. Sleeping for 15 minutes.

**Comment by r4izen** [comment]
I got the same problem in all of the releases , but when I restored windows firewall defaults I worked for me , go to firewall settings or open file explorer and paste : "Control Panel\System and Security\Windows Firewall" without quotes then click RESTORE DEFAULTS , see if this helps .
