### ISSUE TITLE
I cant play while boosting.

### ISSUE THREAD

**Issue by astapkoo** [Ezzpify/HourBoostr#74]
When I want to play while HoursBooster is running, it stops working.
"Warn: Password was not accepted".
I use 1.9.2 ver. Help me please 
http://f1.s.qip.ru/yDSsDtA3.png

**Comment by sapphyrus** [comment]
That's normal, you need to use [SingleBoostr](https://github.com/Ezzpify/HourBoostr/tree/master/SingleBoostr) when you want to play on the account at the same time
