### ISSUE TITLE
can i get vac ban? cs go

### ISSUE THREAD

**Issue by wojtex1** [Ezzpify/HourBoostr#77]
can i get vac ban in cs go, when i am playing cs go while im boosting  other games with SingleBoostr at the same time.

My english is so bad, sorry ;)

**Comment by Ezzpify** [comment]
No. But valve recently updated their list of softwares that might interfere with VAC, and idlers are now listed. That means that you might get kicked because of "Something on your computer is blocking VAC" - but you will NOT get vac banned for using it.
