### ISSUE TITLE
HourBoostr stopped working.

### ISSUE THREAD

**Issue by TheBARNZ** [Ezzpify/HourBoostr#8]
Hello, 
I have a problem with the application, for a long time work correctly, but now i have problem to run it.
It gives me this error: https://scr.hu/65JPp4

I tried to install a program once again, but without effect.
Sorry for my bad englando, im still learning XD

**Comment by Ezzpify** [comment]
Hello, can you screenshot the console window for me please?
I'm talking about the window in the background, black with bunch of white text.

Also, can you try and make a new Settings.json? Delete the one you have and create a new one with the json helper.

**Comment by TheBARNZ** [comment]
https://scr.hu/w2My39

Yes i have tried. Still doesnt work

**Comment by Ezzpify** [comment]
Go to %appdata%\Local\HourBoostr and delete the files there and try again

**Comment by TheBARNZ** [comment]
Thanks for help, its working now :)
