### ISSUE TITLE
Compile issue

### ISSUE THREAD

**Issue by EclipseWWB** [Ezzpify/HourBoostr#85]
we need images of buttons and stuff for single bootr please.

**Comment by Ezzpify** [comment]
Good point lol. Will push media folder later tonight when I'm home.

**Comment by EclipseWWB** [comment]
Thank you :D

**Comment by Ezzpify** [comment]
@EclipseWWB I uploaded media files now. Sorry it came a bit later, was tired yesterday. Had an 18 hour travel day.
