### ISSUE TITLE
Could not read Settings.json

### ISSUE THREAD

**Issue by dztunc** [Ezzpify/HourBoostr#86]
system.colletcions.generic.ireadonlydictionary2 assembly mscorlib,verdion=4.0.0.0, culture=neutral,
Help?

**Comment by Ezzpify** [comment]
Is this for HourBoostr or SingleBoostr?

**Comment by jere021099** [comment]
Hello, same for me on my VPS, this is for the both versions

**Comment by jere021099** [comment]
Consultez la fin de ce message pour plus de détails sur l'appel du débogage
juste-à-temps (JIT) à la place de cette boîte de dialogue.

************** Texte de l'exception **************
System.TypeLoadException: Impossible de charger le type 'System.Collections.Generic.IReadOnlyDictionary`2' à partir de l'assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
   à Newtonsoft.Json.Utilities.CollectionUtils.IsDictionaryType(Type type)
   à Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract(Type objectType)
   à Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveContract(Type type)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   à Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   à Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   à SingleBoostr.SettingsForm.SaveSettings()
   à SingleBoostr.SettingsForm..ctor()
   à SingleBoostr.MainForm.MainForm_Load(Object sender, EventArgs e)
   à System.Windows.Forms.Form.OnLoad(EventArgs e)
   à System.Windows.Forms.Form.OnCreateControl()
   à System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   à System.Windows.Forms.Control.CreateControl()
   à System.Windows.Forms.Control.WmShowWindow(Message& m)
   à System.Windows.Forms.Control.WndProc(Message& m)
   à System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   à System.Windows.Forms.Form.WmShowWindow(Message& m)
   à System.Windows.Forms.Form.WndProc(Message& m)
   à System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   à System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   à System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Assemblys chargés **************
mscorlib
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.0.30319.1 (RTMRel.030319-0100)
    CodeBase : file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
SingleBoostr
    Version de l'assembly : 3.0.1.0
    Version Win32 : 3.0.1
    CodeBase : file:///C:/Users/Administrateur/Desktop/Single%20hour%20booster/SingleBoostr.exe
----------------------------------------
System.Windows.Forms
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.0.30319.1 built by: RTMRel
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.0.30319.1 built by: RTMRel
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.0.30319.1 built by: RTMRel
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
Newtonsoft.Json
    Version de l'assembly : 10.0.0.0
    Version Win32 : 10.0.1.20720
    CodeBase : file:///C:/Users/Administrateur/Desktop/Single%20hour%20booster/Newtonsoft.Json.DLL
----------------------------------------
System.Core
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.0.30319.1 built by: RTMRel
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Numerics
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.0.30319.1 built by: RTMRel
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Windows.Forms.resources
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.0.30319.1 built by: RTMRel
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_fr_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
mscorlib.resources
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.0.30319.1 (RTMRel.030319-0100)
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_fr_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------

************** Débogage JIT **************
Pour activer le débogage juste-à-temps (JIT), le fichier de configuration pour cette
application ou cet ordinateur (machine.config) doit avoir la valeur
jitDebugging définie dans la section system.windows.forms.
L'application doit également être compilée avec le débogage
activé.

Par exemple :

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

Lorsque le débogage juste-à-temps est activé, les exceptions non gérées
seront envoyées au débogueur JIT inscrit sur l'ordinateur
plutôt que d'être gérées par cette boîte de dialogue.

**Comment by Ezzpify** [comment]
Try running as admin or set up the settings on your own PC then transfer to vps. Folder seems to be readonly.

**Comment by jere021099** [comment]
That doesn't work :/ The program doesn't crash anymore but the idling doesn't work.

**Comment by Ezzpify** [comment]
Are no accounts getting logged in or what is the problem?

**Comment by jere021099** [comment]
![hours booster error](https://cloud.githubusercontent.com/assets/27271656/24906592/9df4c696-1eb8-11e7-86da-9efe11cd792f.png)

That's what happen when i try to open hourboostr.exe or the settings.exe

**Comment by Ezzpify** [comment]
Reading the setting shouldn't be a problem. If you have made the Settings.json file on your own pc and then transferred it to the VPS, just run Hourboostr.exe directly, and not through Settings.exe

**Comment by jere021099** [comment]
It's ok now i just installed Windows Server 2012 R2 instead of the 2008 version and everything works fine :)
