### ISSUE TITLE
Hourboostr Causing Steam To Lose Connection To Network

### ISSUE THREAD

**Issue by RookB** [Ezzpify/HourBoostr#95]
When I run Hourboostr ( v 3.1.0 ) Steam instantly loses connection to internet. Going into offline, or rebooting Steam and/or my computer doesn't affect it.  It seems to boot up perfectly fine: 
![screenshot 12](https://cloud.githubusercontent.com/assets/27941050/25322232/0ce32d8a-2883-11e7-82a1-e03d868cc6f0.png) But this will happen to Steam, which causes the Hours not to register, rendering Hourboostr ineffective.  :<)         
![screenshot 13](https://cloud.githubusercontent.com/assets/27941050/25322279/785d6ada-2883-11e7-97ba-40c75980b5be.png)

**Comment by Ezzpify** [comment]
Use singleboostr if you want to use your account at the same time. If you had only read the big README.
